project: kyouku.xcodeproj
schemes:
- kyouku

# App-centric scan settings (reduce common false positives).
exclude_tests: true
retain_codable_properties: true
retain_assign_only_properties: true
retain_objc_accessible: true
retain_swift_ui_previews: true

# Cosmetic / focus: redundant `public` warnings aren't “dead code”.
disable_redundant_public_analysis: true
relative_results: true
